language: bash
dist: focal
sudo: required

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

env:
  global:
    - TAG=0.16.0.0-rc3

before_install:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.12~3-0~ubuntu-focal
  - docker version
  - docker info
  - docker buildx version

install:
  - git clone https://github.com/docker-library/official-images.git official-images

before_script:
  - image="strophy/dashd:$TAG"

script:
  - docker build -t "$image" .
  - official-images/test/run.sh "$image"
  - test/run.sh "$image"

after_script:
  - docker images

after_failure:
  - sudo systemctl status docker.service
  - sudo journalctl -xe

# vim:set et ts=2 sw=2:
