language: bash
dist: focal
sudo: required

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
  jobs:
    - BUILD=dashd
    - BUILD=dashd-develop

before_install:
  - sudo apt-get -y install docker-ce
  - |
    if [ $BUILD == "dashd" ]; then
      export TAG=$(curl https://api.github.com/repos/dashpay/dash/releases/latest -s | jq .tag_name -r | cut -c2-)
    else
      export TAG=$(curl https://api.github.com/repos/dashpay/dash/tags -s | jq .[0].name -r | cut -c2-)
    fi

install:
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  #- git clone https://github.com/docker-library/official-images.git official-images
  - docker buildx create --name xbuilder --use

before_script:
  - image="strophy/$BUILD:$TAG"
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker buildx build --push --build-arg VERSION="$TAG" --platform linux/amd64,linux/arm64,linux/arm/v7 -t "$image" .
  #- official-images/test/run.sh "$image"
  #- test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
