language: bash
dist: focal
sudo: required
services: docker

env:
  global:
    - TAG=0.16.0.0-rc3
    - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

install:
  - git clone https://github.com/docker-library/official-images.git official-images

before_script:
  - image="strophy/dashd:$TAG"
  - docker version
  - docker buildx version

script:
  - docker build -t "$image" .
  - official-images/test/run.sh "$image"
  - test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
