language: bash
dist: focal
sudo: required

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

env:
  global:
    - TAG=0.16.0.0-rc3
    - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - docker run --rm --privileged docker/binfmt

install:
  - sudo apt-get -y install docker-ce
  - git clone https://github.com/docker-library/official-images.git official-images
  - docker buildx create --name xbuilder --use

before_script:
  - image="strophy/dashd:$TAG"
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker buildx build --push --build-arg VERSION="$TAG" --platform linux/amd64,linux/arm64,linux/arm/v7 -t "$image" .
  #- official-images/test/run.sh "$image"
  #- test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
