language: bash
dist: focal
services: docker

env:
  - TAG=0.16.0.0-rc3
  - DOCKER_CLI_EXPERIMENTAL=enabled

install:
  - git clone https://github.com/docker-library/official-images.git official-images

before_script:
  - env | sort
  - image="strophy/dashd:$TAG"
  - docker buildx version

script:
  - docker build -t "$image" .
  - official-images/test/run.sh "$image"
  - test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
